---
version: "2"         # required to adjust maintainability checks

checks:
  method-complexity:
    enabled: true
    config:
      threshold: 10
  argument-count:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 1000
