---
name: Publish

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published

jobs:
  publish:
    name: Publish
    runs-on: 'ubuntu-latest'
    steps:

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -

      - name: Add Poetry to $PATH
        run: |
          echo "$HOME/.poetry/bin" >> $GITHUB_PATH

      - name: Poetry Check
        run: poetry check --no-interaction

      - name: Python Packages Cache
        id: cached-python-dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-poetry-packages
        with:
          path: ${{ github.workspace }}/.venv
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/poetry.lock') }}

      - name: Poetry Install
        if: steps.cached-python-dependencies.cache-hit != 'true'
        run: |
          poetry config virtualenvs.in-project true
          poetry install --no-interaction

      - name: Poetry Publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN_PYPI }}
        run: |
          poetry publish --no-interaction --build
